"""Add area configuration fields to zones table

Revision ID: 82ae1753e56d
Revises: f11a31aeb3e1
Create Date: 2025-07-12 14:37:10.328590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ae1753e56d'
down_revision = 'f11a31aeb3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settlement_density', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('average_household_charge', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('waste_generation_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('socioeconomic_level', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_column('socioeconomic_level')
        batch_op.drop_column('waste_generation_rate')
        batch_op.drop_column('average_household_charge')
        batch_op.drop_column('settlement_density')

    # ### end Alembic commands ###
