"""Add is_external_auth column to users

Revision ID: f11a31aeb3e1
Revises: 
Create Date: 2025-06-30 11:27:48.166344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11a31aeb3e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zoning_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_external_auth', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zoning_users', schema=None) as batch_op:
        batch_op.drop_column('is_external_auth')

    # ### end Alembic commands ###
